// <auto-generated />
using System;
using APITemplate.DataAccess.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APITemplate.DataAccess.Migrations
{
    [DbContext(typeof(APITemplateContext))]
    partial class APITemplateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APITemplate.Entity.Poco.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedIPV4Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedIPV4Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedTime = new DateTime(2024, 9, 18, 5, 42, 5, 761, DateTimeKind.Utc).AddTicks(383),
                            Guid = new Guid("ffdf1936-5e41-49c8-976f-06568cbf37de"),
                            IsActive = true,
                            Name = "Admin",
                            UpdatedTime = new DateTime(2024, 9, 18, 5, 42, 5, 761, DateTimeKind.Utc).AddTicks(384)
                        },
                        new
                        {
                            Id = 2,
                            AddedTime = new DateTime(2024, 9, 18, 5, 42, 5, 761, DateTimeKind.Utc).AddTicks(387),
                            Guid = new Guid("5910b8a6-e4f2-4819-a71b-b6494e514ffa"),
                            IsActive = true,
                            Name = "Çalışan",
                            UpdatedTime = new DateTime(2024, 9, 18, 5, 42, 5, 761, DateTimeKind.Utc).AddTicks(388)
                        });
                });

            modelBuilder.Entity("APITemplate.Entity.Poco.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedIPV4Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedIPV4Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedTime = new DateTime(2024, 9, 18, 8, 42, 5, 760, DateTimeKind.Local).AddTicks(9067),
                            Email = "admin@gmail.com",
                            Guid = new Guid("78bda474-0196-40e9-849c-2ad2ddec3ff8"),
                            Image = "string",
                            IsActive = true,
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "123",
                            UpdatedTime = new DateTime(2024, 9, 18, 8, 42, 5, 760, DateTimeKind.Local).AddTicks(9080)
                        });
                });

            modelBuilder.Entity("APITemplate.Entity.Poco.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedIPV4Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedIPV4Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedTime = new DateTime(2024, 9, 18, 8, 42, 5, 761, DateTimeKind.Local).AddTicks(3877),
                            Guid = new Guid("19c84e60-1c6f-4a7f-bc9b-cfe20fcdc0b8"),
                            IsActive = true,
                            RoleId = 1,
                            UpdatedTime = new DateTime(2024, 9, 18, 8, 42, 5, 761, DateTimeKind.Local).AddTicks(3881),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("APITemplate.Entity.Poco.UserRole", b =>
                {
                    b.HasOne("APITemplate.Entity.Poco.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("APITemplate.Entity.Poco.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APITemplate.Entity.Poco.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("APITemplate.Entity.Poco.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
